#ifndef __P389_FIND_THE_DIFFERENCE_H__
#define __P389_FIND_THE_DIFFERENCE_H__

#include "header.h"

namespace leetcode {
namespace p389_find_the_difference {

/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (57.29%)
 * Likes:    1092
 * Dislikes: 304
 * Total Accepted:    241.1K
 * Total Submissions: 419.5K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 * Example 1:
 *
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 *
 * Example 2:
 *
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Example 3:
 *
 *
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 *
 * Example 4:
 *
 *
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 *
 *
 * Constraints:
 *
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 *
 *
 */

// @lc code=start
class Solution {
 public:
  char findTheDifference(string s, string t) {
    int n = 0;
    for (auto i : s) {
      n ^= i;
    }
    for (auto i : t) {
      n ^= i;
    }
    return (char)n;
  }
};
// @lc code=end

}  // namespace p389_find_the_difference
}  // namespace leetcode
#endif  // __P389_FIND_THE_DIFFERENCE_H__
